FROM registry.cn-hangzhou.aliyuncs.com/alinux/aliyunlinux:latest

LABEL maintainer="Shirong Hao <shirong@linux.alibaba.com>"

# Install alinux-release-experimentals prior to others to work around
# the issue "Error: Package: glibc-2.17-323.1.al7.i686 (updates)"
RUN yum install -y alinux-release-experimentals

ENV PROTOBUF_VERSION 2.5.0

RUN yum install -y \
    which wget git make autoconf libtool openssl yum-utils \
    libseccomp-devel binutils-devel openssl-devel openssl-devel devtoolset-9-toolchain \
    protobuf-devel-$PROTOBUF_VERSION protobuf-c-devel-$PROTOBUF_VERSION

RUN echo "source /opt/rh/devtoolset-9/enable" > /root/.bashrc

WORKDIR /root

# install go
RUN wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz && \
    tar -zxvf go1.14.2.linux-amd64.tar.gz -C /usr/lib && \
    rm -f go1.14.2.linux-amd64.tar.gz

# configure GOPATH and GOROOT
ENV GOROOT       /usr/lib/go
ENV GOPATH       /root/gopath
ENV PATH         $PATH:$GOROOT/bin:$GOPATH/bin
ENV GOPROXY      "https://mirrors.aliyun.com/goproxy,direct"
ENV GO111MODULE  on

# install SGX
RUN yum-config-manager --add-repo \
	https://enclave-cn-beijing.oss-cn-beijing-internal.aliyuncs.com/repo/alinux/enclave-expr.repo

RUN yum install -y teesdk libsgx-dcap-quote-verify-devel libsgx-dcap-ql-devel libsgx-uae-service
