FROM registry.cn-hangzhou.aliyuncs.com/alinux/aliyunlinux

LABEL maintainer="YiLin Li <YiLin.Li@linux.alibaba.com>"

RUN yum clean all && yum install -y alinux-release-experimentals

ENV PROTOBUF_VERSION 2.5.0

RUN yum install -y \
    which wget git make autoconf libtool openssl yum-utils \
    libseccomp-devel binutils-devel openssl-devel openssl-devel devtoolset-9-toolchain \
    protobuf-devel-$PROTOBUF_VERSION protobuf-c-devel-$PROTOBUF_VERSION

RUN echo "source /opt/rh/devtoolset-9/enable" > /root/.bashrc

WORKDIR /root

RUN mkdir /root/gopath

# install go
RUN wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz && \
    tar -zxvf go1.14.2.linux-amd64.tar.gz -C /usr/lib && \
    rm -rf go1.14.2.linux-amd64.tar.gz

# configure GOPATH and GOROOT
ENV GOROOT       /usr/lib/go
ENV GOPATH       /root/gopath
ENV PATH         $PATH:$GOROOT/bin:$GOPATH/bin
ENV GO111MODULE  on

# install docker
RUN yum install -y iptables && \
    wget https://download.docker.com/linux/static/stable/x86_64/docker-19.03.8.tgz && \
    tar -zxvf docker-19.03.8.tgz && mv docker/* /usr/bin && rm -rf docker && rm docker-19.03.8.tgz

# configure the rune runtime of docker
RUN mkdir -p /etc/docker && \
    echo -e "{\n\t\"runtimes\": {\n\t\t\"rune\": {\n\t\t\t\"path\": \"/usr/local/bin/rune\",\n\t\t\t\"runtimeArgs\": []\n\t\t}\n\t}\n}" >> /etc/docker/daemon.json

# install SGX
RUN yum-config-manager --add-repo \
        https://enclave-cn-beijing.oss-cn-beijing-internal.aliyuncs.com/repo/alinux/enclave-expr.repo

RUN yum install -y teesdk libsgx-dcap-quote-verify-devel libsgx-dcap-ql-devel libsgx-uae-service
